const app = new Vue({
    el: "#app",
    data: {
        projects: [
            // contribute 值为 1 表示自己的项目，为 2 表示与他人合作的他人的项目
            {
                displayName: "mcsmC",
                projectName: "mcsmC",
                identifier: "io.github.kyln24.mcsmC",
                repository: "https://www.github.com/KYLN24/mcsmC",
                contribute: 1,
                description: "Minecraft Server Manager Commandline Tool",
            },
            {
                displayName: "旦兮",
                projectName: "DanXi",
                identifier: "io.github.w568w.dan_xi",
                repository: "https://www.github.com/w568w/DanXi",
                contribute: 2,
                description: "可能是为 FDUer 准备的,最好的一站式服务 APP!",
            },
            {
                displayName: "旦兮",
                projectName: "DanXi",
                identifier: "io.github.w568w.dan_xi",
                repository: "https://www.github.com/w568w/DanXi",
                contribute: 2,
                description: "可能是为 FDUer 准备的,最好的一站式服务 APP!",
            },
            {
                displayName: "旦兮",
                projectName: "DanXi",
                identifier: "io.github.w568w.dan_xi",
                repository: "https://www.github.com/w568w/DanXi",
                contribute: 2,
                description: "可能是为 FDUer 准备的,最好的一站式服务 APP!",
            },
            {
                displayName: "旦兮",
                projectName: "DanXi",
                identifier: "io.github.w568w.dan_xi",
                repository: "https://www.github.com/w568w/DanXi",
                contribute: 2,
                description: "可能是为 FDUer 准备的,最好的一站式服务 APP!",
            },
            {
                displayName: "旦兮",
                projectName: "DanXi",
                identifier: "io.github.w568w.dan_xi",
                repository: "https://www.github.com/w568w/DanXi",
                contribute: 2,
                description: "可能是为 FDUer 准备的,最好的一站式服务 APP!",
            },
            {
                displayName: "旦兮",
                projectName: "DanXi",
                identifier: "io.github.w568w.dan_xi",
                repository: "https://www.github.com/w568w/DanXi",
                contribute: 2,
                description: "可能是为 FDUer 准备的,最好的一站式服务 APP!",
            },
            {
                displayName: "旦兮",
                projectName: "DanXi",
                identifier: "io.github.w568w.dan_xi",
                repository: "https://www.github.com/w568w/DanXi",
                contribute: 2,
                description: "可能是为 FDUer 准备的,最好的一站式服务 APP!",
            },
            {
                displayName: "旦兮",
                projectName: "DanXi",
                identifier: "io.github.w568w.dan_xi",
                repository: "https://www.github.com/w568w/DanXi",
                contribute: 2,
                description: "可能是为 FDUer 准备的,最好的一站式服务 APP!",
            },
        ],
    },
});
